# Generated by Django 3.1 on 2020-08-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Naver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Naver name")),
                ("birthdate", models.DateField(verbose_name="Birth date")),
                (
                    "admission_date",
                    models.DateField(auto_now_add=True, verbose_name="Admission date"),
                ),
                ("job_role", models.CharField(max_length=30, verbose_name="Job role")),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="projects",
                        to="project.Project",
                        verbose_name="Projects",
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
    ]
