# Generated by Django 3.1 on 2020-08-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200815_1402"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="naver", new_name="navers",
        ),
    ]
